alsa_hw_mapping: plughw:1,0
beep: /home/admin/rotary-phone-audio-guestbook/sounds/beep.wav
beep_include_in_message: true
beep_start_delay: 0.0
beep_volume: 1.0
channels: 2
file_type: wav
format: cd
greeting: /home/admin/rotary-phone-audio-guestbook/sounds/greeting.wav
greeting_start_delay: 1.5
greeting_volume: 1.0
hook_bounce_time: 0.1
hook_gpio: 22
hook_type: NC
mixer_control_name: Speaker
record_greeting_bounce_time: 0.1
record_greeting_gpio: 23
record_greeting_type: NC
recording_limit: 300
recordings_path: /home/admin/rotary-phone-audio-guestbook/recordings
sample_rate: 44100
time_exceeded: /home/admin/rotary-phone-audio-guestbook/sounds/time_exceeded.wav
time_exceeded_length: 300
time_exceeded_volume: 1.0
